### ISSUE TITLE
alternator resolution fix

### ISSUE THREAD

**Issue by hitch3ns** [BlackChaplin/Apex-AimAssist-NoRecoil-2023#1]
hi , thanks for your effort updating this can you ensure that 1680x1050 alternator update for just standard weapon detection i just need the resolution line for it , thanks 

here is a screenshot 
![Uploading WhatsApp Image 2023-12-07 at 7.59.34 PM.jpeg…]()

**Comment by BlackChaplin** [comment]
I updated the file and it should be detected correctly now. Write how you test it. And if it’s not difficult, take a screenshot with GS so that you can also do the correct tracking
[1680x1050.zip](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/files/13603782/1680x1050.zip)

**Comment by hitch3ns** [comment]
and quick question how safe gold optic is, i have been avoiding it since it was introduced case many claim ban cause of it.

**Comment by BlackChaplin** [comment]
> and quick question how safe gold optic is, i have been avoiding it since it was introduced case many claim ban cause of it.

It's hard to say exactly. It's just software that tracks red spots and guides your aim towards them, it's not at all the same as, for example, aim cheat. Unless it will be noticeable to your teammates when they look from your camera (when they are waiting for resurrection) that your aim moves a little unnaturally. Yes, and it works quite buggy, perhaps we’ll have to abandon it altogether

**Comment by hitch3ns** [comment]
i guess for the good, my friend tried it alternator = "1342,902,1,1378,926,1,1374,913,0" its not working btw yet mine works well on 1080

**Comment by BlackChaplin** [comment]
> i guess for the good, my friend tried it alternator = "1342,902,1,1378,926,1,1374,913,0" its not working btw yet mine works well on 1080

Is it not defined at all or is it defined incorrectly?

**Comment by BlackChaplin** [comment]
> zero detection, the pattern is ok but the detection like none.

It should work fine with these parameters. For some reason, your screenshot that I downloaded from another group was of incorrect resolution, I had to launch the game myself and set the required resolution =)
alternator = "1405,952,1,1441,960,0,1459,953,1"
