### ISSUE TITLE
Functional question inquiry

### ISSUE THREAD

**Issue by sjiebn** [BlackChaplin/Apex-AimAssist-NoRecoil-2023#10]
What can I do to preserve only the recoil? Remove other features, because I think the more features the easier it is for EA to detect

**Comment by BlackChaplin** [comment]
> What can I do to preserve only the recoil? Remove other features, because I think the more features the easier it is for EA to detect

Specially for you:
[apexmaster.zip](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/files/14655056/apexmaster.zip)
Copy with replacement

**Comment by sjiebn** [comment]
Thank you so much. After using your software yesterday, you are a fucking genius. If I could sponsor you, I would definitely offer it.

**Comment by BlackChaplin** [comment]
> Thank you so much. After using your software yesterday, you are a fucking genius. If I could sponsor you, I would definitely offer it.

Tell me, do you happen to have an open master weapon?

**Comment by sjiebn** [comment]
> > Thank you so much. After using your software yesterday, you are a fucking genius. If I could sponsor you, I would definitely offer it.
> 
> Tell me, do you happen to have an open master weapon?

I'm sorry, I don't quite understand your sentence, my English is not very good

**Comment by BlackChaplin** [comment]
> I'm sorry, I don't quite understand your sentence, my English is not very good

Just like mine) When you raise the level of a weapon to level 100 or higher, it becomes a master weapon and its color changes.

**Comment by sjiebn** [comment]
> > I'm sorry, I don't quite understand your sentence, my English is not very good
> 
> Just like mine) When you raise the level of a weapon to level 100 or higher, it becomes a master weapon and its color changes.

Are you talking about master weapons? I don't have a level 100 weapon yet, so I'm sorry I can't help you in this regard
