### ISSUE TITLE
hi，it's me.1728X1080 question

### ISSUE THREAD

**Issue by COLORFUL123311** [BlackChaplin/Apex-AimAssist-NoRecoil-2023#2]
HI，sorry for back later，this is all the gun‘s which can use gs's screenshots ，and 【VOLT SMG ，Revenge Repeater，HEMLOK AR】，can“t work in 1728X1080，I'll be eternally grateful to you for it If you can make it work.Have a nice day♥
![20231208040050_1](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/ccf50e59-00b6-4599-966e-bf09b7ac205b)
![20231208040056_1](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/7d21712c-4fb4-40b4-beeb-1774e7e96e8c)
![20231208040108_1](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/830d75e1-c342-4f02-994d-5be2ae1408e4)
![20231208040115_1](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/a784d414-e41d-4937-baf7-4525d960eb8f)
![20231208040125_1](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/7c9a78cd-d6f5-4834-8c2c-20279605d8f7)

**Comment by COLORFUL123311** [comment]
And i find a problem.IF I first use weapon1【others weapon】 shoot then change weapon2【Revenge and HEMLOK are in weapon2】，the Revenge and HEMLOK can work，but if I first use weapon2【Revenge and HEMLOK】，it can't be work。。vice versa .  Can u fix it？ thanks a lot ♥

**Comment by COLORFUL123311** [comment]
T.T Orz

**Comment by BlackChaplin** [comment]
Try this option to see if GS is detected correctly. And also please check if there is a false definition when you place the x2 sight (false definition of x2 as GS)
[1728x1080.zip](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/files/13609401/1728x1080.zip)

**Comment by COLORFUL123311** [comment]
when i take Hemlok or Revenge，the voice say 【Triple take】，I'm not sure if it's this sound but i hear it。IN the first weapon ，the Hemlok or Revenge completely ineffective。But when in the second weapon，If I first use first weapon shoot like use Car，Hem and revenge can use，，T.T

**Comment by COLORFUL123311** [comment]
and i find the other resolution have same question，Hemlok or Revenge can‘t work

**Comment by COLORFUL123311** [comment]
https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/3b9e90e5-85a7-4b95-bcb1-b1f137c687b6

**Comment by BlackChaplin** [comment]
> when i take Hemlok or Revenge，the voice say 【Triple take】，I'm not sure if it's this sound but i hear it。IN the first weapon ，the Hemlok or Revenge completely ineffective。But when in the second weapon，If I first use first weapon shoot like use Car，Hem and revenge can use，，T.T

Very strange, TRIPLETAKE is detected only when it is an energy weapon and none of the weapon options match the pixel coordinates. Don't you have any blind mod?

**Comment by BlackChaplin** [comment]
Please send me a screenshot with the HEMLOK weapon in both hands (first when the first weapon is selected, and then when the second is selected) And the same with any energy weapon

**Comment by COLORFUL123311** [comment]
> > when i take Hemlok or Revenge，the voice say 【Triple take】，I'm not sure if it's this sound but i hear it。IN the first weapon ，the Hemlok or Revenge completely ineffective。But when in the second weapon，If I first use first weapon shoot like use Car，Hem and revenge can use，，T.T
> 
> Very strange, TRIPLETAKE is detected only when it is an energy weapon and none of the weapon options match the pixel coordinates. Don't you have any blind mod?
I don"t know why ,i don't selecet any blind mod..
![微信图片_20231209034329](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/926b77df-320f-47e2-af5d-f59a7ad7e9ba)

**Comment by COLORFUL123311** [comment]
> Please send me a screenshot with the HEMLOK weapon in both hands (first when the first weapon is selected, and then when the second is selected) And the same with any energy weapon

![20231209034730_1](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/e3c87a3e-d521-4ad3-a10d-5677837ac1a0)
![20231209034749_1](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/bfacac6a-1fea-4f91-9040-17164f7f035f)
![20231209034801_1](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/d94452ed-9d0f-4d2c-97e8-adb1cf4cdb58)
Thanks for help again，u can see it .Must thank you in here me, was laborious♥

**Comment by BlackChaplin** [comment]
You didn't quite understand me. Make screenshots with 2 heavy weapons, the first screen when the first weapon is selected, and the second when the second one (it can be the same weapon just in 2 slots) And the same with the energy one

**Comment by COLORFUL123311** [comment]
> You didn't quite understand me. Make screenshots with 2 heavy weapons, the first screen when the first weapon is selected, and the second when the second one (it can be the same weapon just in 2 slots) And the same with the energy one

okay，dose this time right？all the guns In the screenshots can't work，Thanks for help♥
![20231209171406_1](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/0d53d55a-c56c-4884-b516-27daaf9decd2)
![20231209171413_1](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/48330bb7-da8d-4893-8e71-c7a57d6e27ec)
![20231209171424_1](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/6de15a8a-a563-4275-ac0f-05a92122a2de)
![20231209171431_1](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/bd65893c-bf7c-42fc-a92c-1c9d3aa43dcf)
![20231209171441_1](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/6365e4df-c673-478d-9ad6-94cbdfa37abc)
![20231209171448_1](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/44f3ebdf-2318-42e2-be21-ffbfe1fcba71)
![20231209171457_1](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/27a2a2aa-af95-4264-9a6a-97db0c0df7c5)
![20231209171503_1](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/eb23aff7-f8d9-4573-a90c-584303a283b9)

**Comment by BlackChaplin** [comment]
There was no logic for detecting and interacting with Nemesis weapons in my build at all. This is why this weapon was not identified. I had to borrow the logic from the respected mgsweet ([https://github.com/mgsweet/Apex-NoRecoil-2021](url)) I checked it at a resolution of 1920*1080 - it works properly (check it on yours) I also calibrated the pixel coordinates of weapons that were not detected for you, check now.
Unpack the archive to the root of the program
[apexmaster.zip](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/files/13624234/apexmaster.zip)

**Comment by COLORFUL123311** [comment]
> There was no logic for detecting and interacting with Nemesis weapons in my build at all. This is why this weapon was not identified. I had to borrow the logic from the respected mgsweet ([https://github.com/mgsweet/Apex-NoRecoil-2021](url)) I checked it at a resolution of 1920*1080 - it works properly (check it on yours) I also calibrated the pixel coordinates of weapons that were not detected for you, check now. Unpack the archive to the root of the program [apexmaster.zip](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/files/13624234/apexmaster.zip)

HI ,thanks for help me a lot,but i try,it's can't work in 1728X1080 either,,and when i take this apexmaster.zip in the root of the program.The procedure  have something wrong,When I entered the shooting range, the mouse was moving by itself i can‘t control it，and it fire automatically

**Comment by BlackChaplin** [comment]
> > There was no logic for detecting and interacting with Nemesis weapons in my build at all. This is why this weapon was not identified. I had to borrow the logic from the respected mgsweet ([https://github.com/mgsweet/Apex-NoRecoil-2021](url)) I checked it at a resolution of 1920*1080 - it works properly (check it on yours) I also calibrated the pixel coordinates of weapons that were not detected for you, check now. Unpack the archive to the root of the program [apexmaster.zip](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/files/13624234/apexmaster.zip)
> 
> HI ,thanks for help me a lot,but i try,it's can't work in 1728X1080 either,,and when i take this apexmaster.zip in the root of the program.The procedure have something wrong,When I entered the shooting range, the mouse was moving by itself i can‘t control it，and it fire automatically

Are your game controls set to default? The fact is that everything works correctly for me at a resolution of 1920*1080. That is, there is no violation in the logic and the only thing that differs is the resolution file in which the pixel coordinates are indicated. Completely remove the assembly you currently have, download a new one (it already has all the fixes I made) and unpack it. Also return the game controls to default values.

**Comment by COLORFUL123311** [comment]
> > > There was no logic for detecting and interacting with Nemesis weapons in my build at all. This is why this weapon was not identified. I had to borrow the logic from the respected mgsweet ([https://github.com/mgsweet/Apex-NoRecoil-2021](url)) I checked it at a resolution of 1920*1080 - it works properly (check it on yours) I also calibrated the pixel coordinates of weapons that were not detected for you, check now. Unpack the archive to the root of the program [apexmaster.zip](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/files/13624234/apexmaster.zip)
> > 
> > 
> > HI ,thanks for help me a lot,but i try,it's can't work in 1728X1080 either,,and when i take this apexmaster.zip in the root of the program.The procedure have something wrong,When I entered the shooting range, the mouse was moving by itself i can‘t control it，and it fire automatically
> 
> Are your game controls set to default? The fact is that everything works correctly for me at a resolution of 1920*1080. That is, there is no violation in the logic and the only thing that differs is the resolution file in which the pixel coordinates are indicated. Completely remove the assembly you currently have, download a new one (it already has all the fixes I made) and unpack it. Also return the game controls to default values.

OK thanks i try it later♥

**Comment by COLORFUL123311** [comment]
There will be a voice prompt when the program is opened,and can‘t ture it off，is it normal？and it usually Identify the target and fire, and I have no control over it。。。like open color aimassist

**Comment by BlackChaplin** [comment]
Show us with what settings you run the script

**Comment by COLORFUL123311** [comment]
![1](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/59edbf08-9e3b-4b1d-9023-fed204fbf7a5)

**Comment by BlackChaplin** [comment]
> ![1](https://private-user-images.githubusercontent.com/152357153/289307471-59edbf08-9e3b-4b1d-9023-fed204fbf7a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNTAzOTcsIm5iZiI6MTcwMjE1MDA5NywicGF0aCI6Ii8xNTIzNTcxNTMvMjg5MzA3NDcxLTU5ZWRiZjA4LTllM2ItNGIxZC05MDIzLWZlZDIwNGZiZjdhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQxOTI4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NThiYjZiMzdlNDQ3MWI0OGIzYmQzNDhiZjRjYzIxMTEwMjQxYzNmOWE1NzBiYzA5NGQyMTUzNTlmZTNkZWVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3QwaY456rpPp_NOIC7_zyFhnXZ9vgu1Tvb53mZNSv-s)

This is not my program

**Comment by COLORFUL123311** [comment]
> > ![1](https://private-user-images.githubusercontent.com/152357153/289307471-59edbf08-9e3b-4b1d-9023-fed204fbf7a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNTAzOTcsIm5iZiI6MTcwMjE1MDA5NywicGF0aCI6Ii8xNTIzNTcxNTMvMjg5MzA3NDcxLTU5ZWRiZjA4LTllM2ItNGIxZC05MDIzLWZlZDIwNGZiZjdhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQxOTI4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NThiYjZiMzdlNDQ3MWI0OGIzYmQzNDhiZjRjYzIxMTEwMjQxYzNmOWE1NzBiYzA5NGQyMTUzNTlmZTNkZWVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3QwaY456rpPp_NOIC7_zyFhnXZ9vgu1Tvb53mZNSv-s)
> 
> This is not my program

emm,Sorry，Perhaps I misunderstood， I see you wrote this connection 【https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/issues/url】

**Comment by COLORFUL123311** [comment]
> > ![1](https://private-user-images.githubusercontent.com/152357153/289307471-59edbf08-9e3b-4b1d-9023-fed204fbf7a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNTAzOTcsIm5iZiI6MTcwMjE1MDA5NywicGF0aCI6Ii8xNTIzNTcxNTMvMjg5MzA3NDcxLTU5ZWRiZjA4LTllM2ItNGIxZC05MDIzLWZlZDIwNGZiZjdhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQxOTI4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NThiYjZiMzdlNDQ3MWI0OGIzYmQzNDhiZjRjYzIxMTEwMjQxYzNmOWE1NzBiYzA5NGQyMTUzNTlmZTNkZWVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3QwaY456rpPp_NOIC7_zyFhnXZ9vgu1Tvb53mZNSv-s)
> 
> This is not my program 

Sincere apology，I set the new package [apexmaster.zip]，and in 1920X1080 Nemesis can use but hem can‘use， HEMLOK can‘t use。then in the new package of 1720X1080 all the guns can’t work，the old one of 1720X1080 can work

**Comment by BlackChaplin** [comment]
you can show me on discord how you launch the program and then enter the game and the process of the program

**Comment by COLORFUL123311** [comment]
![123](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/89102535-89fe-406b-8691-240869735a26)
and i find when i delete 78572e and 7c522c，all guns can work in the new of 1728X1080，unless hemlok Volt ，Alternator

**Comment by BlackChaplin** [comment]
> ![123](https://private-user-images.githubusercontent.com/152357153/289309804-89102535-89fe-406b-8691-240869735a26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNTIxMzIsIm5iZiI6MTcwMjE1MTgzMiwicGF0aCI6Ii8xNTIzNTcxNTMvMjg5MzA5ODA0LTg5MTAyNTM1LTg5ZmUtNDA2Yi04NjkxLTI0MDg2OTczNWEyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQxOTU3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2RkNDg0OWE1NGVmNTIxMjI3NzVhOWY1MmUyNWZkNmRmODBkOTM4NThjMmI0NTgyM2FjODEyMTBhMzI3MGZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OASwhnygfChEUClo-qtMI1y_7z34qyzJ0baTDT2Sn60) and i find when i delete 78572e and 7c522c，all guns can work in the new of 1728X1080，unless hemlok Volt ，Alternator

oh damn.. completely forgot about that. I was tracking the colors and forgot to remove them from the file

**Comment by COLORFUL123311** [comment]
first I turn the gui.ahk open，and open the game

**Comment by COLORFUL123311** [comment]
> > ![123](https://private-user-images.githubusercontent.com/152357153/289309804-89102535-89fe-406b-8691-240869735a26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNTIxMzIsIm5iZiI6MTcwMjE1MTgzMiwicGF0aCI6Ii8xNTIzNTcxNTMvMjg5MzA5ODA0LTg5MTAyNTM1LTg5ZmUtNDA2Yi04NjkxLTI0MDg2OTczNWEyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQxOTU3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2RkNDg0OWE1NGVmNTIxMjI3NzVhOWY1MmUyNWZkNmRmODBkOTM4NThjMmI0NTgyM2FjODEyMTBhMzI3MGZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OASwhnygfChEUClo-qtMI1y_7z34qyzJ0baTDT2Sn60) and i find when i delete 78572e and 7c522c，all guns can work in the new of 1728X1080，unless hemlok Volt ，Alternator
> 
> oh damn.. completely forgot about that. I was tracking the colors and forgot to remove them from the file

hh never mind ，You are a very skilled programmer

**Comment by COLORFUL123311** [comment]
and Can hemlok Volt and Alternator work in the 1728x1080？the Nemesis can work now♥

**Comment by COLORFUL123311** [comment]
> and Can hemlok Volt and Alternator work in the 1728x1080？the Nemesis can work now♥

the Volt and alternator can work now uncless hemlok。。

**Comment by BlackChaplin** [comment]
Did you download the assembly from here? (https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023). I gave a link in the posts above, but I wrote there that I borrowed the logic for Nemesis from "mgsweet" and inserted a link to his GitHub. Just based on the screenshots, you are using his version, not mine
Here's my build:
[Apex-AimAssist-NoRecoil-2023-main.zip](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/files/13625575/Apex-AimAssist-NoRecoil-2023-main.zip)

**Comment by COLORFUL123311** [comment]
Good morning,I just get up,YES ,I  have using your build, ALL the gun can use unless HEMlok 
![1](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/764ec0ae-52f6-4086-8def-f3ac56729ac5)

**Comment by COLORFUL123311** [comment]
https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/e7472f55-0110-4c1a-9041-cbf68b059f1c

when i TAKE hemlok the sounds like this. I don't know what's mean

**Comment by BlackChaplin** [comment]
> when i TAKE hemlok the sounds like this. I don't know what's mean

Default. This means it does not detect weapons. Okay, I'll try to look for new pixels for the correct definition

**Comment by BlackChaplin** [comment]
Try these coordinates.
hemlok = "1425,984,1,1447,982,0,1521,990,1"

**Comment by COLORFUL123311** [comment]
> Try these coordinates. hemlok = "1425,984,1,1447,982,0,1521,990,1"
thanks ,I added it in 1728X1080,The sound it can say hemlock，but when i shoot，it’s still can‘t work

**Comment by BlackChaplin** [comment]
Please send 2 screenshots of Hemlok weapons with normal shooting mode and with single

**Comment by COLORFUL123311** [comment]
![20231210164219_1](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/c10e06ef-8d60-4c75-8e2f-3409560e13e5)
![20231210164226_1](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/4b3414d0-3aab-4306-b1c5-e6cfec45d484)
![20231210164233_1](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/4c4f270e-14a8-4ba0-a60f-8752342764da)
![20231210164240_1](https://github.com/BlackChaplin/Apex-AimAssist-NoRecoil-2023/assets/152357153/e2ec2fb1-447a-4792-841e-ec99ccea0f9e)
OK u can see it thanks~♥

**Comment by BlackChaplin** [comment]
Try changing the coordinates
single_mode = "1541,1009"

**Comment by BlackChaplin** [comment]
Also, in order for single_mode to work, you need to activate the auto_fire checkbox in the program settings

**Comment by COLORFUL123311** [comment]
> Also, in order for single_mode to work, you need to activate the auto_fire checkbox in the program settings

thanks I tried，I change the coordinates and open the auto_fire ， but it‘s still can’t work

**Comment by BlackChaplin** [comment]
Made the correct definition of single_mode on Hemlok. Now auto_fire works correctly, but the pattern is bad, so I don’t know if it will help you or not. Redownload the build

**Comment by COLORFUL123311** [comment]
OK thanks a lot，single mode not work very well，I usually use normal shooting with hemlock，Thanks for help me a lot，If there is a better solution in the future, please leave me a message again~Have a nice day♥
