### ISSUE TITLE
 golden sight problem

### ISSUE THREAD

**Issue by Aleax2016** [BlackChaplin/Apex-AimAssist-NoRecoil-2023#4]
thank you for your creation，but，The golden sight has an obvious delayed response. Can I improve the aiming response speed? I increased the speed to 20 in the settings and there was an obvious delayed response.

**Comment by Aleax2016** [comment]
My DPI is 1600, gaming mouse speed is 1.4, APS 0.8

**Comment by Aleax2016** [comment]
My DPI is 1600, gaming mouse speed is 1.4, ADS 0.8，Golden aiming feels like the delay is relatively high

**Comment by BlackChaplin** [comment]
> thank you for your creation，but，The golden sight has an obvious delayed response. Can I improve the aiming response speed? I increased the speed to 20 in the settings and there was an obvious delayed response.

The golden sight function generally works very buggy at the moment, perhaps in the future we will have to abandon it altogether

**Comment by Aleax2016** [comment]
I think it works well. The main reason is that the tracking speed is a bit slow. It would be better if the tracking speed was faster.

**Comment by Aleax2016** [comment]
I used to play Overwatch and used AHK, which basically aimed red at the head in real time.

**Comment by Aleax2016** [comment]
APEX red aiming is slower
